import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// const sidebars: SidebarsConfig = {
//     // By default, Docusaurus generates a sidebar from the docs folder structure
//     tutorialSidebar: [{
//         type: 'autogenerated', dirName: '.'
//     }],

//     // But you can create a sidebar manually
//     /*
//     tutorialSidebar: [
//       'intro',
//       'hello',
//       {
//         type: 'category',
//         label: 'Tutorial',
//         items: ['tutorial-basics/create-a-document'],
//       },
//     ],
//      */
// };

const sidebars: SidebarsConfig = {
    tutorialSidebar: [
        'introduction',
        'hardware_overview',
        'hardware_hookup',
        'system-operation',
        {
            type: 'category',
            label: 'Settings',
            link: {
                type: 'generated-index'
            },
            collapsed: false,
            items: [
                {
                    type: 'category',
                    label: 'General',
                    link: {
                        type: 'generated-index'
                    },
                    collapsed: false,
                    items: [
                        'settings/general/gen-app-set',
                        'settings/general/gen-time-setup',
                        'settings/general/gen-save-settings'
                    ]
                },
                {
                    type: 'category',
                    label: 'Network',
                    link: {
                        type: 'generated-index'
                    },
                    collapsed: true,
                    items: [
                        'settings/network/net-wifi-setup',
                        'settings/network/net-ntp-setup'
                    ]
                },
                {
                    type: 'category',
                    label: 'Logging',
                    link: {
                        type: 'generated-index'
                    },
                    collapsed: true,
                    items: [
                        'settings/logging/log-settings-logger',
                        'settings/logging/log-settings-timer',
                        'settings/logging/log-settings-file',
                        'settings/logging/log-settings-interrupt',
                    ]
                },
                {
                    type: 'category',
                    label: 'GPIO Devices',
                    link: {
                        type: 'generated-index'
                    },
                    collapsed: true,
                    items: [
                        'settings/gpio-devices/gpio-extern-serial',
                        'settings/gpio-devices/gpio-soil-moisture',
                        'settings/gpio-devices/gpio-analog-pin-sensor'
                    ]
                },
                {
                    type: 'category',
                    label: 'Services',
                    link: {
                        type: 'generated-index'
                    },
                    collapsed: false,
                    items: [
                        {
                            type: 'category',
                            label: 'IoT Services',
                            link: {
                                type: 'generated-index'
                            },
                            collapsed: true,
                            items: [
                                'settings/services/iot-services/iot_mqtt',
                                'settings/services/iot-services/iot_aws',
                                'settings/services/iot-services/iot_thingspeak',
                                'settings/services/iot-services/iot_azure',
                                'settings/services/iot-services/iot_http',
                                'settings/services/iot-services/iot_arduino_iot_cloud'
                            ]
                        },
                        "settings/services/iot_web_server"
                    ]
                },
                {
                    type: 'category',
                    label: 'Advanced',
                    link: {
                        type: 'generated-index'
                    },
                    collapsed: true,
                    items: [
                        'settings/advanced/adv-system-update'
                    ]
                }
            ]
        },
        {
            type: 'category',
            label: 'Device Settings',
            link: {
                type: 'generated-index'
            },
            collapsed: true,
            items: [
                'device-settings/gnss-pps-log'
            ]
        },
        {
            type: 'category',
            label: 'Resources',
            link: {
                type: 'generated-index'
            },
            collapsed: true,
            items: [
                'resources/prepare_your_microsd_card',
                'resources/ref-serial-terms',
                'resources/resources',          
                'resources/supported_devices',
                'resources/release_notes',
                'resources/suggested-reading'                            
            ]
        },
        {
            type: 'category',
            label: 'Support',
            link: {
                type: 'generated-index'
            },
            collapsed: true,
            items: [
                'support/troubleshooting',
                'support/file_issue',
                'support/contribute'
            ]
        }
    ]
};

export default sidebars;
